name = "devhub"
default_domain = "devhub"

[constants]
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"

[featured_articles]
"home" = ["/how-to/nextjs-building-modern-applications", "/how-to/python-starlette-stitch", "/how-to/graphql-support-atlas-stitch", "/quickstart/free-atlas-cluster"]
"learn" = ["/quickstart/java-setup-crud-operations", "/how-to/golang-alexa-skills", "/how-to/polymorphic-pattern"]

[page_groups]
"Java Tutorials" = ["/quickstart/java-setup-crud-operations", "/quickstart/java-mapping-pojos", "/quickstart/java-aggregation-pipeline", "/quickstart/java-change-streams"]
"BSON Tutorials" = ["/quickstart/bson-data-types-decimal128", "/quickstart/bson-data-types-objectid"]
"SQL to MongoDB" = ["/article/map-terms-concepts-sql-mongodb", "/article/top-4-reasons-to-use-mongodb"]
"Schema Design Patterns" = ["/how-to/polymorphic-pattern", "/how-to/attribute-pattern"]
