name = "devhub"
default_domain = "devhub"

[constants]
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"

[page_groups]
"home" = ["/how-to/use-union-all-aggregation-pipeline-stage", "/how-to/unit-test-realm-serverless-functions", "/how-to/mongoimport-guide", "/how-to/Realm-AWS-Kinesis-Firehose-Destination"]
"learn" = ["/how-to/creating-multiplayer-drawing-game-phaser", "/how-to/nextjs-building-modern-applications", "/article/building-service-based-atlas-management"]
"Java Tutorials" = ["/quickstart/java-setup-crud-operations", "/quickstart/java-mapping-pojos", "/quickstart/java-aggregation-pipeline", "/quickstart/java-change-streams"]
"BSON Tutorials" = ["/quickstart/bson-data-types-decimal128", "/quickstart/bson-data-types-objectid", "/quickstart/bson-data-types-date"]
"SQL to MongoDB" = ["/article/map-terms-concepts-sql-mongodb", "/article/top-4-reasons-to-use-mongodb", "/article/3-things-to-know-switch-from-sql-mongodb"]
"Schema Design Patterns" = ["/how-to/polymorphic-pattern", "/how-to/attribute-pattern", "/how-to/bucket-pattern", "/how-to/outlier-pattern", "/how-to/computed-pattern", "/how-to/subset-pattern"]
"MongoDB Schema Design Anti-Patterns" = ["/article/schema-design-anti-pattern-massive-arrays", "/article/schema-design-anti-pattern-massive-number-collections", "/article/schema-design-anti-pattern-unnecessary-indexes", "/article/schema-design-anti-pattern-bloated-documents", "/article/schema-design-anti-pattern-separating-data", "/article/schema-design-anti-pattern-case-insensitive-query-index", "/article/schema-design-anti-pattern-summary"]
"COVID-19" = ["/article/coronavirus-map-live-data-tracker-charts", "/article/johns-hopkins-university-covid-19-data-atlas", "/article/johns-hopkins-university-covid-19-rest-api"]
"Maps and Geospatial Data" = ["/how-to/location-geofencing-stitch-mapbox", "/how-to/real-time-location-updates-stitch-change-streams-mapbox", "/how-to/searching-nearby-points-interest-mapbox"]
"MongoDB Atlas Data Lake" = ["/how-to/atlas-data-lake-setup", "/how-to/atlas-data-lake-federated-queries-out-aws-s3", "/how-to/atlas-data-lake-online-archive"]
"Speaker Program" = ["/community/community-speaker-grant","/community/apply-to-speak","/community/art-of-creating-talk","/community/creating-stunning-slides","/community/surviving-the-stage","/community/virtual-presentation"]
"learnPageExclude" =["/community/apply-to-speak","/community/art-of-creating-talk","/community/community-speaker-grant","/community/creating-stunning-slides","/community/speaker-program","/community/surviving-the-stage","/community/virtual-presentation"]
