name = "devhub"
default_domain = "devhub"

[constants]
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"

[page_groups]
"home" = ["/article/johns-hopkins-university-covid-19-data-atlas", "/how-to/strapi-headless-cms-with-atlas", "/quickstart/python-quickstart-crud", "/how-to/graphql-support-atlas-stitch"]
"learn" = ["/article/schema-design-anti-pattern-massive-number-collections", "/how-to/5-ways-reduce-costs-atlas", "/article/build-newsletter-website-mongodb-data-platform"]
"Java Tutorials" = ["/quickstart/java-setup-crud-operations", "/quickstart/java-mapping-pojos", "/quickstart/java-aggregation-pipeline", "/quickstart/java-change-streams"]
"BSON Tutorials" = ["/quickstart/bson-data-types-decimal128", "/quickstart/bson-data-types-objectid", "/quickstart/bson-data-types-date"]
"SQL to MongoDB" = ["/article/map-terms-concepts-sql-mongodb", "/article/top-4-reasons-to-use-mongodb", "/article/3-things-to-know-switch-from-sql-mongodb"]
"Schema Design Patterns" = ["/how-to/polymorphic-pattern", "/how-to/attribute-pattern", "/how-to/bucket-pattern", "/how-to/outlier-pattern", "/how-to/computed-pattern", "/how-to/subset-pattern"]
"MongoDB Schema Design Anti-Patterns" = ["/article/schema-design-anti-pattern-massive-arrays", "/article/schema-design-anti-pattern-massive-number-collections"]
